### ISSUE TITLE
同学你好，我在复现EMNIST-Letters数据集时出现了一些问题

### ISSUE THREAD

**Issue by Isjacky** [zaocan666/AF-FCL#3]
运行的是：python main.py --dataset EMNIST-Letters --data_split_file ./data_split/EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.pkl --num_glob_iters 10 --local_epochs 15 --lr 1e-4 --flow_lr 1e-4 --k_loss_flow 0.5 --k_flow_lastflow 0.4 --flow_explore_theta 0
报错为：
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    main(args)
  File "main.py", line 30, in main
    run_job(args, args.seed)
  File "main.py", line 25, in run_job
    server = create_server_n_user(args, seed)
  File "main.py", line 16, in create_server_n_user
    server=FedPrecise(args, model, i)
  File "/home/aiswjtu/yzy/AF-FCL/FLAlgorithms/servers/serverPreciseFCL.py", line 19, in __init__
    self.data = get_dataset(args, args.dataset, args.datadir, args.data_split_file)
  File "/home/aiswjtu/yzy/AF-FCL/utils/dataset.py", line 121, in get_dataset
    testify_client_y_list(train_y_list, split_data['train_inds'], split_data['client_y_list'])
  File "/home/aiswjtu/yzy/AF-FCL/utils/dataset.py", line 16, in testify_client_y_list
    assert y_c_t_set==set(client_y_list[c_i][t_i])
AssertionError

![image](https://github.com/zaocan666/AF-FCL/assets/89766390/1829e341-dd28-48d9-a32a-b86e8faa37a4)

**Comment by zaocan666** [comment]
这是生成的EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.pkl出现问题，可以把文件发我看看吗

**Comment by Isjacky** [comment]
[Uploading EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.csv…]()

**Comment by Isjacky** [comment]
> 这是生成的EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.pkl出现问题，可以把文件发我看看吗

同学你好，这份文件有什么问题呀

**Comment by Isjacky** [comment]
[Uploading EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.zip…]()

**Comment by zaocan666** [comment]
这两个文件我都下载不了，把文件上传到这里吧
https://cloud.tsinghua.edu.cn/u/d/b2d7cebc0642444c95fa/

> Uploading EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.zip…

**Comment by Isjacky** [comment]
> 这两个文件我都下载不了，把文件上传到这里吧 https://cloud.tsinghua.edu.cn/u/d/b2d7cebc0642444c95fa/
> 
> > Uploading EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.zip…

已经上传啦

**Comment by zaocan666** [comment]
同学，已经修了split_dataset.py中的bug（commit `b2bf13e`），是合并不同数据集代码时出现的bug。现在重新生成data split 文件应该可以跑了
